'use client';
import {useEffect,useMemo,useState} from 'react';
import {parseFile,type Draft} from '../../lib/parse';
type Entry=Draft&{supplier:string;date:string;file:string};
const KEY='ereza-congelados-v1';
const suppliers=['Canary Meat','Grupo Chacón'];
const norm=(s:string)=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
export default function Congelados(){
 const [rows,setRows]=useState<Entry[]>([]),[supplier,setSupplier]=useState(suppliers[0]),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[preview,setPreview]=useState<Draft[]>([]),[file,setFile]=useState(''),[error,setError]=useState(''),[ready,setReady]=useState(false),[search,setSearch]=useState('');
 useEffect(()=>{try{setRows(JSON.parse(localStorage.getItem(KEY)||'[]'))}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(rows))},[rows,ready]);
 async function upload(f:File){setError('');setPreview([]);try{setPreview(await parseFile(f));setFile(f.name);if(/chacon|chacón/i.test(f.name))setSupplier('Grupo Chacón');if(/canary/i.test(f.name))setSupplier('Canary Meat')}catch(e){setError(String(e))}}
 const latest=useMemo(()=>{const map=new Map<string,Entry>();for(const r of rows){const k=r.supplier+'|'+(r.code||norm(r.name))+'|'+r.unit;const prev=map.get(k);if(!prev||r.date>=prev.date)map.set(k,r)}return [...map.values()]},[rows]);
 const grouped=useMemo(()=>{const map=new Map<string,Entry[]>();for(const r of latest){const k=norm(r.name)+'|'+r.unit;map.set(k,[...(map.get(k)||[]),r])}return [...map.entries()].filter(([k])=>k.includes(norm(search))).map(([key,items])=>({key,items,best:Math.min(...items.map(i=>i.price))})).sort((a,b)=>a.key.localeCompare(b.key))},[latest,search]);
 const euro=(n:number)=>n.toLocaleString('es-ES',{style:'currency',currency:'EUR'});
 function exportCSV(){const data=[['Artículo','Unidad','Proveedor','Precio','Mejor precio','Diferencia','Fecha'],...grouped.flatMap(g=>g.items.map(r=>[r.name,r.unit,r.supplier,String(r.price),String(g.best),String(r.price-g.best),r.date]))];const csv='\uFEFF'+data.map(r=>r.map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='ereza-congelados.csv';a.click();URL.revokeObjectURL(a.href)}
 return <main className="shell"><header className="top"><div><span className="eyebrow">EREZA · CENTRAL DE COMPRAS</span><h1>Comparador de congelados</h1><p>Canary Meat · Grupo Chacón · histórico de tarifas</p></div><a href="/">← Comparador general</a></header>
 <section className="card"><h2>Importar tarifa</h2><p>Sube los archivos PDF, Excel o CSV recibidos por Outlook. La lectura automática del correo todavía no está conectada.</p><div className="formgrid"><label>Proveedor<select value={supplier} onChange={e=>setSupplier(e.target.value)}>{suppliers.map(s=><option key={s}>{s}</option>)}</select></label><label>Vigencia<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Archivo<input type="file" accept=".pdf,.xlsx,.xls,.csv" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/></label></div>{error&&<p className="error">{error}</p>}{preview.length>0&&<><p>{preview.length} líneas detectadas en {file}. Comprueba unidades y equivalencias antes de guardar.</p><div className="tablewrap preview"><table><thead><tr><th>Artículo</th><th>Precio</th><th>Unidad</th></tr></thead><tbody>{preview.map((r,i)=><tr key={i}><td>{r.name}</td><td>{euro(r.price)}</td><td><select value={r.unit} onChange={e=>setPreview(p=>p.map((x,j)=>j===i?{...x,unit:e.target.value as Draft['unit']}:x))}><option value="kg">kg</option><option value="ud">ud</option><option value="l">l</option></select></td></tr>)}</tbody></table></div><button onClick={()=>{setRows(r=>[...r,...preview.map(p=>({...p,supplier,date,file}))]);setPreview([])}}>Guardar tarifa</button></>}</section>
 <section className="card"><h2>Comparativa</h2><p>Coincidencias exactas de nombre normalizado y unidad. Los productos con nombres diferentes requieren homologación manual; no se comparan automáticamente.</p><input placeholder="Buscar producto" value={search} onChange={e=>setSearch(e.target.value)}/><div className="tablewrap"><table><thead><tr><th>Artículo</th><th>Proveedor</th><th>Precio</th><th>Diferencia con mínimo</th><th>Vigencia</th></tr></thead><tbody>{grouped.flatMap(g=>g.items.map((r,i)=><tr key={g.key+r.supplier+i}><td>{r.name} ({r.unit})</td><td>{r.supplier}</td><td>{euro(r.price)}</td><td>{euro(r.price-g.best)}</td><td>{r.date}</td></tr>))}</tbody></table></div><p>{grouped.length} artículos · {rows.length} líneas históricas · almacenamiento local en este navegador</p><button onClick={exportCSV}>Exportar CSV</button></section></main>
}